import 'package:easy_localization/easy_localization.dart';
import 'package:flutter/widgets.dart';

const Map<String, dynamic> kTestTranslations = {
  'tab_parcel': 'Parcel',
  'tab_send_parcel': 'Send',
  'tab_notifications': 'Notifications',
  'tab_profile': 'Profile',
  'tab_contact': 'Contact',
  'tab_receive': 'Receive',
  'tab_scan_pay': 'Scan Pay',
  'tab_branch': 'Branches',
  'tab_customer_chat': 'Customer Chat',
  'switch_branch': 'SWITCH BRANCH',
  'switch_to_customer': 'SWITCH TO CUSTOMER',
  'language_english': 'English',
  'language_lao': 'Lao',
  'language_chinese': 'Chinese',
  'topbar_menu': 'Top menu',
  'logout': 'Logout',
  'logout_success': 'Logged out successfully',
  'logout_failed': 'Logout failed, please try again',
  'your_parcels': 'Your Parcels',
  'receive_incoming_parcels': 'Receive Incoming Parcels',
  'step_scan_box': 'Step 1: Scan or register parcel box',
  'search_parcel_or_item': 'Search tracking no. or item...',
  'search_receive_parcel': 'Search parcel for receiving...',
  'parcel_claim_entry_title': 'Find My Parcel',
  'parcel_claim_entry_subtitle': 'Search unowned parcels and request ownership',
  'parcel_claim_title': 'Claim Parcel Ownership',
  'parcel_claim_intro':
      'Select the parcels that belong to you, then submit a claim for review',
  'parcel_claim_search_hint': 'Search tracking no. or name...',
  'parcel_claim_phone_label': 'Phone: {}',
  'parcel_claim_phone_missing':
      "We couldn't find your phone number. Please sign in again",
  'parcel_claim_total_label': '{} parcels found',
  'parcel_claim_empty': 'No unowned parcels found',
  'parcel_claim_search_prompt':
      'Enter the full tracking number to find your parcel',
  'parcel_claim_page_label': 'Page {} of {}',
  'parcel_claim_selected_count': '{} selected',
  'parcel_claim_selected_title': 'Selected parcels',
  'parcel_claim_clear_selection': 'Clear all',
  'parcel_claim_submit_button': 'Confirm these parcels are mine',
  'parcel_claim_confirm_title': 'Confirm claim',
  'parcel_claim_confirm_message': 'Submit a claim for {} parcel(s)?',
  'parcel_claim_confirm_action': 'Confirm',
  'common_cancel': 'Cancel',
  'parcel_claim_submit_success':
      'Claim request submitted. Please wait for admin approval',
  'parcel_claim_load_error': 'Failed to load unowned parcels',
  'parcel_claim_submit_error': 'Failed to submit claim request',
  'parcel_claim_validation_error':
      'Please check your phone number and selected parcels',
  'status_waiting_inspection': 'Waiting for Inspection',
  'status_ready_to_ship': 'Ready to Ship',
  'status_shipping_started': 'Shipping Started',
  'status_wait_import': 'Awaiting Import',
  'status_pending': 'Pending',
  'status_ready': 'Ready for Pickup',
  'action_pickup': 'Pickup',
  'action_forward': 'Forward',
  'action_confirm_inspected': 'Confirm Inspection',
  'new_tag': 'NEW',
  'no_parcel_found': 'No parcels match your search',
  'no_receive_found': 'No incoming parcels match your search',
  'action_not_implemented': 'This action is coming soon',
  'send_select_title': 'Select parcel to forward',
  'send_select_subtitle':
      'Please select one parcel from your list to continue sending',
  'send_next_button': 'Next: Recipient details',
  'send_recipient_title': 'Recipient details',
  'send_selected_parcel_label': 'Selected parcel',
  'send_recipient_name_label': 'Recipient name',
  'send_recipient_name_hint': 'Enter recipient full name',
  'send_recipient_phone_label': 'Recipient phone number',
  'send_recipient_phone_hint': '0xx-xxx-xxxx',
  'send_recipient_address_label': 'Recipient address',
  'send_recipient_address_hint': 'House no., alley, road...',
  'send_courier_label': 'Courier service',
  'send_courier_hint': 'e.g. Flash, J&T',
  'send_branch_label': 'Delivery branch',
  'send_branch_hint': 'Select branch',
  'send_pin_address_button': 'Next: Pin address (Google Maps)',
  'send_pin_title': 'Pin recipient address',
  'send_pin_instruction': 'Click or tap to pin recipient location',
  'send_pin_coordinate_label': 'Destination coordinates for parcel {}',
  'send_next_summary_button': 'Next: Order summary & payment',
  'send_payment_title': 'Forwarding payment',
  'send_payment_order_label': 'Forwarding item',
  'send_payment_destination': 'Destination: {}',
  'send_payment_weight_billed': 'Weight: {} kg (billed {} kg)',
  'send_payment_fee_label': 'Forwarding fee',
  'send_payment_vat_label': 'VAT (7%)',
  'send_payment_total_label': 'Total',
  'send_payment_confirm_button': 'Confirm forwarding {}',
  'send_forward_success_message': 'Forwarding completed successfully',
  'send_map_placeholder': 'Map preview is disabled in widget tests',
  'notifications_title': 'Notifications',
  'notifications_count_label': '{} items',
  'notifications_item_forwarded_title': 'Forwarding completed',
  'notifications_item_forwarded_message':
      'Your parcel has been successfully forwarded through k (k)',
  'notifications_item_forwarded_time': '15 May, 20:06',
  'notifications_item_welcome_title': 'Welcome to QuickPick!',
  'notifications_item_welcome_message':
      'Get updates to track your parcels quickly and easily',
  'notifications_item_welcome_time': '15 May, 12:22',
  'contact_title': 'Help/Contact Staff',
  'contact_welcome_message': 'Welcome to support. Ask parcel status now!',
  'contact_input_hint': 'Type your message...',
  'contact_auto_reply': 'Received: {}. Staff will reply shortly.',
  'profile_user_name': 'Somchai Rakdee',
  'profile_user_email': 'somchai@email.com',
  'profile_summary_processing': 'Processing',
  'profile_summary_received': 'Received',
  'profile_summary_at_home': 'At home',
  'profile_summary_completed': 'Completed',
  'profile_active_parcels_title': 'Parcels in progress',
  'profile_received_history_title': 'Service history',
  'profile_home_delivery_history_title': 'Home delivery history',
  'profile_completed_history_title': 'Delivery history',
  'profile_home_delivery_empty_message': 'No home delivery history',
  'profile_parcel_air_fryer_forwarding': '[Forwarding to k] Phillips Air Fryer',
  'profile_parcel_headphones': 'Sony WH-1000XM5 Headphones',
  'profile_parcel_one_piece': 'One Piece Figure Vol.100',
  'profile_parcel_weight': '{} kg',
  'profile_status_received': 'Received',
  'profile_status_completed': 'Completed',
  'profile_step_sent': 'Sent',
  'profile_step_ready': 'Ready',
  'profile_step_pickup': 'Waiting pickup',
  'profile_step_success': 'Done',
  'profile_current_location_title': 'Current receiver location',
  'profile_current_location_label': 'Current address',
  'profile_pin_map_action': 'Pin on map',
  'profile_current_address_value':
      '123/45 Soi Ruan Sap, Sukhumvit Rd, Bangkok 10110',
  'profile_save_button': 'Save',
  'profile_saved_message': 'Profile location saved',
  'scan_pay_title': 'Scan parcel delivery',
  'scan_pay_subtitle': 'Step 2: Verify QR and send out',
  'scan_pay_live_scanner': 'LIVE SCANNER ACTIVE',
  'scan_pay_camera_permission': 'Request Camera Permissions',
  'scan_pay_scan_image': 'Scan an Image File',
  'scan_pay_scanning_image': 'Scanning image...',
  'scan_pay_camera_denied': 'Camera permission is required to scan QR',
  'scan_pay_no_qr_found': 'No QR code found in selected image',
  'scan_pay_item_title': 'Ready item {}',
  'scan_pay_ready_list': 'Ready to hand over ({})',
  'scan_pay_empty_message': 'No pending handover items',
  'send_back_tooltip': 'Back',
  'send_item_headphones': 'Sony WH-1000XM5 Headphones',
  'send_item_air_fryer': 'Phillips Air Fryer',
  'history': 'History',
  'profile': 'Profile',
  'switch_language': 'Switch language',
  'app_name': 'CLS Global',
  'brand_subtitle': 'Express Pickup Hub',
  'login_continue_subtitle': 'Sign in to continue',
  'register_continue_subtitle': 'Use phone number and password to continue',
  'phone_local_hint': '20 9xxxxx',
  'common_retry': 'Retry',
  'common_back': 'Back',
  'common_previous': 'Previous',
  'common_next': 'Next',
  'common_loading': '...',
  'notifications_empty': 'No notifications yet',
  'notifications_load_error': 'Failed to load notifications',
  'send_empty_selectable_parcels': 'No parcel available for forwarding',
  'send_load_parcels_error': 'Failed to load parcels',
  'send_reselect_parcel': 'Please select a parcel again',
  'send_submit_forward_error': 'Failed to submit forwarding request',
  'history_empty': 'No history yet',
  'history_retry_loading': 'Retry loading history',
  'contact_send_failed': 'Failed to send message',
  'contact_load_error': 'Failed to load chat messages',
  'profile_load_error': 'Failed to load profile parcels',
  'profile_received_history_empty': 'No received history',
  'profile_completed_history_empty': 'No completed history',
  'profile_active_parcels_empty': 'No active parcels',
  'staff_receive_load_error': 'Failed to load incoming parcels',
  'staff_receive_marked_inspected': 'Parcel marked as inspected',
  'staff_receive_update_failed': 'Failed to update parcel status',
  'staff_scan_pay_handover_confirmed': 'Handover confirmed for {}',
  'staff_scan_pay_confirm_failed': 'Failed to confirm handover',
  'staff_scan_pay_confirm_handover': 'Confirm handover',
  'staff_scan_pay_load_error': 'Failed to load ready-to-handover parcels',
  'forgot_password': 'Forgot password?',
  'forgot_password_title': 'Forgot password',
  'forgot_password_subtitle':
      'Enter your registered Lao phone number to receive an OTP',
  'back_to_login': 'Back to login',
  'continue': 'Continue',
  'otp_verified': 'OTP verified',
  'otp_expired_or_not_requested':
      'OTP expired or not requested. Please request a new OTP',
  'phone_not_registered': 'No account found with this phone number',
  'reset_password_title': 'Reset password',
  'reset_password_subtitle':
      'Create a new password. You will need to login again after reset',
  'new_password': 'New password',
  'reset_password': 'Reset password',
  'password_reset_success': 'Password reset successfully. Please login again',
  'password_reset_failed': 'Unable to reset password, please try again',
  'reset_token_invalid_or_expired':
      'Reset token expired or invalid. Please start again',
  'pickup_payment_title': 'Pay for service',
  'pickup_payment_item_label': 'Parcel',
  'pickup_payment_total_label': 'Net total',
  'pickup_payment_method_label': 'Select payment method',
  'pickup_payment_bcel_title': 'BCEL ONE',
  'pickup_payment_bcel_subtitle': 'Scan QR via BCEL ONE App',
  'pickup_payment_card_title': 'Credit / Debit Card',
  'pickup_payment_card_coming_soon': 'Coming soon',
  'pickup_payment_card_unavailable':
      'Credit card payment is coming soon. Please use BCEL ONE',
  'pickup_payment_pay_button': 'Pay now {}',
  'pickup_payment_bcel_qr_caption': 'Save the image or scan via the BCEL ONE app',
  'pickup_payment_qr_progress': 'Parcel {} of {}',
  'pickup_payment_qr_items': '{} parcels',
  'pickup_payment_waiting': 'Waiting for payment confirmation...',
  'pickup_payment_confirm_paid_button': "I've paid",
  'pickup_payment_qr_expired': 'QR code expired. Please generate a new QR code',
  'pickup_payment_new_qr_button': 'Generate new QR',
  'pickup_payment_success_title': 'Payment successful',
  'pickup_payment_success_subtitle': 'Your payment has been confirmed',
  'pickup_payment_done_button': 'Done',
  'pickup_payment_error': 'Payment failed. Please try again',
  'status_title': 'Parcel status',
  'status_track_action': 'Track',
  'status_tab_in_progress': 'In progress',
  'status_tab_self_pickup': 'Self pickup',
  'status_tab_forwarded': 'Forwarded',
  'status_step_arrived': 'Arrived',
  'status_step_ready': 'Ready',
  'status_step_delivering': 'Delivering',
  'status_step_success': 'Done',
  'status_empty': 'No parcels in this category',
  'status_order_pickup': 'Pickup fee',
  'status_order_forward': 'Forwarding fee',
  'status_order_ref': 'Ref: {}',
  'order_history_title': 'Order history',
  'order_history_subtitle': 'View all your pickup & forwarding orders',
  'order_history_empty': 'No orders yet',
  'order_history_type_pickup': 'Pickup order',
  'order_history_type_forward': 'Forwarding order',
  'order_status_paid': 'Paid',
  'order_status_pending': 'Pending',
  'order_status_failed': 'Failed',
};

class MockAssetLoader extends AssetLoader {
  const MockAssetLoader(this.data);

  final Map<String, dynamic> data;

  @override
  Future<Map<String, dynamic>> load(String path, Locale locale) async {
    return data;
  }
}
